cupboard: [0.26485594767589743, 3.128237723913257, 0.661900797154323, 0.7495914452063015]
shelf: [4.225140322446365, -0.3198947784664439, -0.09210990416764805, 0.9957488466246027]
dining_room: [3.831719074363783, 2.6463151947962436, 0.9928201093432615, 0.11961701586160023]
entrance: [6.486645447612806, 2.376898572710941, 0.9942261194715234, 0.10730528114028709]
living_room: [3.482062955025767, -0.5539089938969401, 0.9981876932544915, 0.06017747946929332]
operator: [1.4763157302161738, -0.11923503206680626, -0.07271599447299729, 0.9973526879433389]
desk: [2.176379177344395, 2.7683869480083274, -0.801149373145041, 0.5984644366287005]
